openapi: 3.1.0
info:
  title: Shopping Cart Service
  contact: {}
  version: '1.0'
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema
servers:
- url: http://localhost:3000/api/cart
  description: Local development (Postman, host machine)
  variables: {}
paths:
  /cart:
    get:
      tags:
      - Carts
      summary: Get current user's cart
      operationId: Getcurrentuser'scart
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
      - Carts
      summary: Clear the entire cart
      operationId: Cleartheentirecart
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CleartheentirecartRequest'
              - examples:
                - user_id: '1'
              contentMediaType: application/json
            example:
              user_id: '1'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    parameters: []
  /cart/items:
    post:
      tags:
      - Carts
      summary: Add item to cart
      operationId: Additemtocart
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/AdditemtocartRequest'
              - examples:
                - user_id: '1'
                  product_id: A
                  quantity: '5'
              contentMediaType: application/json
            example:
              user_id: '1'
              product_id: A
              quantity: '5'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    parameters: []
  /cart/items/A:
    put:
      tags:
      - Carts
      summary: Update quantity of item in cart
      operationId: Updatequantityofitemincart
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdatequantityofitemincartRequest'
              - examples:
                - user_id: '1'
                  quantity: 3
              contentMediaType: application/json
            example:
              user_id: '1'
              quantity: 3
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
      - Carts
      summary: Remove item from cart
      operationId: Removeitemfromcart
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/RemoveitemfromcartRequest'
              - examples:
                - user_id: '1'
              contentMediaType: application/json
            example:
              user_id: '1'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    parameters: []
components:
  schemas:
    AdditemtocartRequest:
      title: AdditemtocartRequest
      required:
      - user_id
      - product_id
      - quantity
      type: object
      properties:
        user_id:
          type: string
        product_id:
          type: string
        quantity:
          type: string
      examples:
      - user_id: '1'
        product_id: A
        quantity: '5'
    UpdatequantityofitemincartRequest:
      title: UpdatequantityofitemincartRequest
      required:
      - user_id
      - quantity
      type: object
      properties:
        user_id:
          type: string
        quantity:
          type: integer
          contentEncoding: int32
      examples:
      - user_id: '1'
        quantity: 3
    RemoveitemfromcartRequest:
      title: RemoveitemfromcartRequest
      required:
      - user_id
      type: object
      properties:
        user_id:
          type: string
      examples:
      - user_id: '1'
    CleartheentirecartRequest:
      title: CleartheentirecartRequest
      required:
      - user_id
      type: object
      properties:
        user_id:
          type: string
      examples:
      - user_id: '1'
tags:
- name: Carts
  description: 'API endpoints for managing shopping carts for users'
